### ISSUE TITLE
Error after install on xubuntu

### ISSUE THREAD

**Issue by omidonrails** [hossein4heydari/aricon#3]
بعد از نصب در زوبونتو وقتی پرسید چه فایل منیجری استفاده میکنی تونر نداشت و گزینه هر دو رو انتخاب کردم این خروجی رو گرفتم :

`cp: -r not specified; omitting directory './Aricon-files'
cp: cannot create regular file '/home/omid/.local/share/nautilus/scripts': No such file or directory
cp: cannot create regular file '/home/omid/.local/share/nautilus/scripts': No such file or directory
chmod: cannot access '/home/omid/.local/share/nautilus/scripts/Audio Removal': No such file or directory
chmod: cannot access '/home/omid/.local/share/nautilus/scripts/Video Removal': No such file or directory
cp: cannot create regular file '/home/omid/.local/share/nautilus/scripts': No such file or directory
chmod: cannot access '/home/omid/.local/share/nautilus/scripts/Aricon': No such file or directory
chmod: cannot access '/home/omid/.local/share/nemo/scripts/Audio Removal': No such file or directory
chmod: cannot access '/home/omid/.local/share/nemo/scripts/Video Removal': No such file or directory
cp: cannot create regular file '/home/omid/.local/share/nemo/scripts': No such file or directory
chmod: cannot access '/home/omid/.local/share/nemo/scripts/Aricon': No such file or directory
`

مسلما چون این فایل منیجرارو ندارم

وقتی باز میکنم ارور میده که کامند 
aricon
 وجود نداره

**Comment by hossein4heydari** [comment]
درود

متاسفانه برای Thunar قابل استفاده نیست.

**Comment by hossein4heydari** [comment]
درود، متاسفانه برای تانار قابل استفاده نیست.
